name: Build Android & Desktop

on: [push, pull_request]

jobs: build-android:
  runs-on: ubuntu-latest steps:
- uses: actions/checkout@v3

- name: Set up Haxe
    uses: krdlab/setup-haxe@v1
    with:
      haxe-version: 4.3.3

  - name: Install dependencies
    run: |
      haxelib install lime
      haxelib install openfl
      haxelib install flixel
      haxelib install hxcpp
      haxelib run lime setup -y

  - name: Build Android
    run: haxelib run lime build android -release || haxelib run lime build android -debug

build-desktop:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3

- name: Set up Haxe
    uses: krdlab/setup-haxe@v1
    with:
      haxe-version: 4.3.3

  - name: Install dependencies
    run: |
      haxelib install lime
      haxelib install openfl
      haxelib install flixel
      haxelib install hxcpp
      haxelib run lime setup -y

  - name: Build Desktop (Neko)
    run: haxelib run lime build neko

